### PR TITLE
PERPLEXITY Support Added

### PR DESCRIPTION
**Pull request by ldhiman**
Added Perplexity AI Support, Need to Check before Merging

### CODE REVIEW

**Comment by ldhiman** [comment]
issue #811

**Comment by ldhiman** [comment]
issue #760

**Review by surapuramakhil — APPROVED** [review]

**Comment by 49Simon** [comment]
@ldhiman @surapuramakhil Can we have information about perplexity added to [README](https://github.com/AIHawk-co/Auto_Jobs_Applier_AI_Agent/tree/release/v11.15.2024#21-configyaml---customize-llm-model-endpoint)

**Comment by surapuramakhil** [comment]
yes defiantly

**Pull request merged**
