### PR TITLE
merge V4 feature branch into release 

### PR DESCRIPTION
**Pull request by surapuramakhil**
@queukat it would helpful if you can fill this up

### CODE REVIEW

**Comment by queukat** [comment]
> @queukat it would helpful if you can fill this up

@surapuramakhil These are my older commits. I recommend using this PR instead: https://github.com/AIHawk-co/Auto_Jobs_Applier_AI_Agent/pull/813, as some functions have changed, new ones were added, and so on.

All non-mine commits have been integrated and tested as well.

**Comment by queukat** [comment]
> @queukat it would helpful if you can fill this up
@surapuramakhil 
Just to clarify, V4 is not a feature branch—it’s a major bug-fix release that resolves over 100 bugs, inconsistencies, and issues from main, along with some enhancements. While these improvements might appear feature-like, they primarily address functional gaps. For instance, the new auto-date-filling functionality could be seen as a feature, but it’s essential for fully completing forms for submission.

If the main branch was used for release, that might pose issues, as main still contains many unresolved problems that V4 has already addressed. At least 50 users have been using V4 due to its fixes for issues they reported, which should improve stability significantly.

**Comment by queukat** [comment]
@surapuramakhil  If the release was based on main and the plan is now to update it using V4, that’s not a good approach, as the code and functionality differ significantly. It would be much simpler to move the latest functions directly into V4 and release from there. For example, I’ve already integrated perplexity into V4.

Additionally, there’s over 40% mismatch with the configuration examples, which would also need to be addressed if V4 becomes the base.

**Comment by surapuramakhil** [comment]
> @surapuramakhil **If the release was based on main and the plan is now to update it using V4, that’s not a good approach**, as the code and functionality differ significantly. It would be much simpler to move the latest functions directly into V4 and release from there. For example, I’ve already integrated perplexity into V4.
> 
> Additionally, there’s over 40% mismatch with the configuration examples, which would also need to be addressed if V4 becomes the base.

@queukat main is a much more mature branch than v4, I believe it's used by much more than fifty users. if I understand you correctly, instead of rebasing v4 to main. You are suggesting making v4 as main branch when v4 is released.

I believe the only way to release v4 is by making the main compatible. **We want all bug fixes; features that went into main should be reflected in v4. Discarding it is an extremely bad idea. **

**Comment by queukat** [comment]
> > @surapuramakhil **If the release was based on main and the plan is now to update it using V4, that’s not a good approach**, as the code and functionality differ significantly. It would be much simpler to move the latest functions directly into V4 and release from there. For example, I’ve already integrated perplexity into V4.
> > 
> > Additionally, there’s over 40% mismatch with the configuration examples, which would also need to be addressed if V4 becomes the base.
> 
> @queukat main is a mature branch and v4 is not even Weathered, I believe it's used by much more than fifty users and for a long time. if I understand you correctly, instead of rebasing v4 to main. You are suggesting making v4 as main branch when v4 is released.
> 
> I believe the only way to release v4 is by making the main compatible. **We want all bug fixes; features that went into main should be reflected in v4. Discarding it is an extremely bad idea**. 

@surapuramakhil  Yes, that's correct. Previously, @feder-cr would merge new changes from v4 when bugs came up, but that stopped about a month ago (or maybe longer), and since then, we’ve seen release and hotfix branches appear. I haven’t reviewed what’s new in main since then. Originally, the plan was to transition directly to v4, as was done with v3 and v2.

It’s unclear why this hasn’t been happening and why changes were added to main without going through v4. But yes, now we’ll need to review and test everything thoroughly before releasing.

Also, a new version of the library is coming soon (I’m currently testing it). There aren’t any major changes, but we’ll still need to be cautious.

**Pull request closed without merging**
